// tslint:disable
export const categories = ["Androids",
    "Androids/Cell Saga",
    "Artificial Life Forms",
    "Bond of Master and Disciple",
    "DB Saga",
    "Dragon Ball Heroes",
    "Dragon Ball Seekers",
    "Full Power",
    "Fusion",
    "Future Saga",
    "Giant Form",
    "Ginyu Force",
    "Goku's Family",
    "Hybrid Saiyans",
    "Joined Forces",
    "Kamehameha",
    "Low-Class Warrior",
    "Majin Buu Saga",
    "Movie Bosses",
    "Movie Heroes",
    "Namekians",
    "Otherworld Warriors",
    "Peppy Gals",
    "Planet Namek Saga",
    "Potara",
    "Pure Saiyans",
    "Realm of Gods",
    "Representatives of Universe 7",
    "Resurrected Warriors",
    "Revenge",
    "Shadow Dragon Saga",
    "Siblings' Bond",
    "Super Saiyan 2",
    "Super Saiyan 3",
    "Super Saiyans",
    "Target: Goku",
    "Team Bardock",
    "Terrifying Conquerors",
    "Time Travelers",
    "Transformation Boost",
    "Universe 6",
    "Universe Survival Saga",
    "Vegeta's Family",
    "Wicked Bloodline",
    "World Tournament",
    "Worthy Rivals",
    "Youth",
]